export const CharacterAttribute = {
    NAME: {name: "name"},
    SURNAME: {name: "surname"},
    BIRTHPLACE: {name: "birthPlace"},
    RACE: {name: "race"},
    EYECOLOR: {name: "eyeColor"},
    HAIRCOLOR: {name: "hairColor"},
    STARSIGN: {name: "starSign"},
    BIRTHDATE: {name: "birthDate"},
    BASESTATS: {name: "baseStats"},
    DOMINATINGEMOTIONS: {name: "dominatingEmotions"},
    SEX: {name: "sex"},
    RELIGION: {name: "religion"},
    WEIGHT: {name: "weight"},
    HEIGHT: {name: "height"},
    PREDICTION: {name: "prediction"},
    CURRENTCAREER: {name: "currentCareer"},
    SKILLS: {name: "skills"},
    TALENTS: {name: "talents"},
    PERSONALITY: {name: "personality"},
    APPERANCE: {name: "apperance"},
    LIVEPLACE: {name: "livePlace"},
    CREATEDBY: {name: "createdBy"},
    ENDSTATS: {name: "endStats"}
};