export const religions = [
    "Sigmar",
    "Ulryk",
    "Taal&Rhya",
    "Myrmydia",
    "Shalyia",
    "Morr",
    "Ranald",
    "Manann",
    "Verena",
    "Asuryan",
    "Isha",
    "Kurnous",
    "Hoeth",
    "Vaul",
    "Lileath",
    "Moraiheg",
    "Mathlann",
    "Grungni",
    "Grimnir",
    "Valaya",
    "Khorne",
    "Khaine",
    "Nurgle",
    "Slaanesh",
    "Tzeentch",
    "Stara Wiara",
    "Brak bóstwa opiekuńczego",
    "Inne"
]