export const starSigns = [
    "Bębniarz",
    "Dudy",
    "Dwa byki",
    "Vobist Ulotny",
    "Rozbity Wóz",
    "Tłusty Kozioł",
    "Kocioł Rhyi",
    "Złoty Kogut",
    "Lancet",
    "Gwiazda Uroku",
    "Wymund Pustelnik",
    "Wielki Krzyż",
    "Sznur Limnera",
    "Wół Gnuthus",
    "Smok Dragomas",
    "Gwiazda Wieczorna",
    "Pas Grungniego",
    "Mędrzec Marmit",
    "Głupiec Mummit",
    "Dwa Byki",
    "Tancerka"
]