export const textsPolish = {
    noRecordsOnCharactersList: 'Brak postaci spełniających kryteria',
    toolTipName: "By wygenerować imię potrzeba: ",
    toolTipSurname: "By wygenerować nazwisko potrzeba: ",
    toolTipRace: "By wygenerować rase potrzeba: ",
    toolTipSex: "By wygenerować płeć potrzeba: ",
    toolTipProfession: "By wygenerować profesje potrzebne są imię, nazwisko, rasa, płeć, miejsce urodzenia oraz wszystkie statystyki bazowe",
    toolTipPlaceOfBeing: "By wygenerować miejsce pobytu potrzeba: ",
    toolTipDayOfBorn: "By wygerować całą date urodzenia potrzeba: ",
    toolTipMonthOfBorn: "By wygerować całą date urodzenia potrzeba: ",
    toolTipYearOfBorn: "By wygerować całą date urodzenia potrzeba: ",
    toolTipHeight: "By wygenerować wzrost potrzeba: ",
    toolTipWeight: "By wygenerować wage potrzeba: ",
    toolTipColorOfEyes: "By wygenerować kolor oczu potrzeba: ",
    toolTipColorOfHair: "By wygenerować kolor włosów potrzeba: ",
    toolTipCharacter: "By wygenerować cechy charakteru potrzebne są rasa, profesja, data urodzenia oraz religia",
    toolTipAppearance: "By wygenerować cechy wyglądu potrzebne są rasa, płeć, profesja, data urodzenia, religia, wzrost i waga",
    toolTipPreviousProfession: "Poprzednie profesje zmieniają się przy losowaniu obecnej profesji",
    toolTipReligion: "By wygerować religie potrzeba: ",
    toolTipEmotions: "By wygenerować dominujące emocje potrzeba: ",
    toolTipSkills: "By wygenerować umiejętności potrzeba: ",
    toolTipTalents: "By wygenerować zdolności potrzeba: ",

}