export const textsPolish = {
    noRecordsOnCharactersList: 'Brak postaci spełniających kryteria',
    toolTipMakarena: "makrena",
    toolTipName: "makrena",
    toolTipSurname: "makrena",
    toolTipRace: "makrena",
    toolTipSex: "makrena",
    toolTipProfession: "makrena",
    toolTipPlaceOfBeing: "makrena",
    toolTipPlaceOfBorn: "Miejsce urodzenia jest pierwszą cechą, której potrzebuje generator by generować reszte cech.",
    toolTipDayOfBorn: "makrena",
    toolTipMonthOfBorn: "makrena",
    toolTipYearOfBorn: "makrena",
    toolTipHeight: "makrena",
    toolTipWeight: "makrena",
    toolTipColorOfEyes: "makrena",
    toolTipColorOfHair: "makrena",
    toolTipCharacter: "makrena",
    toolTipAppearance: "makrena",
    toolTipPreviousProfession: "makrena",
    toolTipReligion: "makrena",
    toolTipEmotions: "makrena",
    toolTipSkills: "makrena",
    toolTipTalents: "makrena",
    toolTipAbilities: "makrena",
    toolTipProphecy: "makrena",

}