export const fronendUrls = {
    mainPage: '/',
    characterList: '/characters',
    historyList: '/histories',
    characterDetails: '/characterDetails',
    characterGenerator: '/generator',
    historyCreator: '/history/create',
    loginPage: "/login",
    userProfilePage: "/user",
    registerPage: '/register',
    sessionList: '/sessions',
    sessionDetails: '/session',
    forgotPasswordPage: '/forgotPassword',
    newPasswordPage: "/newPassword",
    cookiesPage: '/cookies',
    activateUser: '/activate-user',
    createCharacterManual: '/manual/createCharacterManual',
    createHistoryManual: '/manual/createHistoryManual',
    sessionManual: '/manual/sessionManual',
    characterHistoryListManual: '/manual/characterHistoryListManual',
    statute: '/statute'
}